##spring.application.name=nini
server:
    port:8082

#spring:
#
#    jpa:
#        properties:
#            hibernate:
#                dialect:  org.hibernate.dialect.H2Dialect
#                show_sql: true
#                format_sql: true
#                use_sql_comments: true
#                ddl-auto: create
#                default_batch_fetch_size: 1000
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#
#    datasource:
#        driver-class-name: org.h2.Driver
#        url:  jdbc:h2:tcp://localhost/~/nini2
#        hikari:
#            username: nini2
#            password: 1234
#

spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/nini2
        username: nini2
        password: 1234
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true